.TH project1 "2021-12-28" ""project1 man 
 
.SH NAME
project1

.SH SYNOPSIS
.B project1
[\fB\ ls \fR]
[\fB\ ls -a \fR]
[\fB\ ls -1 \fR]
[\fB\-d\fR]
[\fB\-\-directory\fR]
[\fB\ mkdir \fR]
[\fB\ touch \fR]
[\fB\ rm \fR]
[\fB\ rmdir \fR]
[\fB\-r\fR]
[\fB\-\-recursive\fR]
[\fB\-R\fR]
[\fB\-d\fR]
[\fB\-\-dir\fR]
[\fB\ cp \fR]
[\fB\-\-help\fR]
[\fB\-\-version\fR]

.SH DESCRIPTION
.B project1
this project manages files and directories : 1-ls which is listing information about files/ directories ,2-rm which is removing files/directories and 3-cp that copy folder with its files to another folder.
.SH OPTIONS
.TP
.BR \ ls 
list all files or directories in the current directory by default.
.TP
.BR \ ls -a 
list all files including hidden files.
.TP
.BR \ ls -1
list all files in "long" format.
.TP
.BR \ -d " , " \-\-directory 
list directories themselves, not their contents. 
.TP
.BR \ mkdir
create a new directory.
.TP
.BR \ touch
create a new file.
.TP
.BR \ rm 
delete a file.
.TP
.BR \ rmdir 
delete a directory.
.TP
.BR \ -r " , " \ -\-recursive " , " \ -R
remove directories and their contents recursively.
.TP
.BR \ -d " , " \ -\-dir
remove empty directories.
.TP
.BR \ cp
copy file from one location to another.
.TP
.BR \ -\-help
display help and exit.
.TP
.BR \ -\-version
output version information and exit.
.SH AUTHOR
written by Nada Mohamed,Farah Tarek,Maryam Sherif,Karim Ragab,Antonious Awad.
